name: data_model
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.14.0=pyhd8ed1ab_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - greenlet=3.3.0=py313h7033f15_0
  - icu=78.2=h33c6efd_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libpq=17.7=hb80d175_2
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - ncurses=6.5=h2d0b736_3
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh145f28c_0
  - psycopg2=2.9.9=py313hd40f53e_2
  - python=3.13.1=ha99a958_105_cp313
  - python_abi=3.13=8_cp313
  - readline=8.3=h853b02a_0
  - sqlalchemy=2.0.36=py313h536fd9c_0
  - tk=8.6.13=noxft_ha0e22de_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6

